[package]
name = "dafu_postgres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "26.0.0"
ipnet = "2.7.2"
tokio = { version = "1.25.0", features = ["macros", "rt", "parking_lot"] }
